GET http://localhost:8087/api/v1/rules/245

###

POST http://localhost:8087/api/v1/rules
Content-Type: application/json

{
    "user_id": "homahmoud@edu.aau.at",
    "metric_type": "battery_capacity",
    "threshold_value": 80.0,
    "condition": "LESS_THAN",
    "delivery_channel": "EMAIL"
}

###

DELETE http://localhost:8087/api/v1/rules/1
